security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        participant_provider:
            entity:
                class: App\Entity\Participant
                property: mail # Adjust if you use a different identifier

    firewalls:
        # Firewall principal pour l'application
        main:
            lazy: true
            provider: participant_provider
            custom_authenticator: App\Security\AppAuthenticator
            form_login:
                login_path: login
                check_path: login

            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            entry_point: form_login  # Définir form_login comme point d'entrée

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
